// gen_cdfs imports github.com/KarpelesLab/goavif/av1/entropy/cdfs and
// emits a single Rust source file containing every Default*CDF table as
// a `pub static` of the appropriately jagged shape. Run after updating
// goavif to resync the tables:
//
//	go run ./tools/gen_cdfs > src/cdfs/generated.rs
//
// The goavif cdfs package exports wire-format CDFs (each CDF is a
// `[]uint16` of length N+1 where the final slot is the update counter
// starting at 0). We copy the bytes verbatim — no interpretation —
// keeping the oxideav-av1 range coder API identical to goavif's.
package main

import (
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/KarpelesLab/goavif/av1/entropy/cdfs"
)

func main() {
	out := os.Stdout
	fmt.Fprintln(out, "// THIS FILE IS GENERATED BY tools/gen_cdfs. DO NOT EDIT BY HAND.")
	fmt.Fprintln(out, "// Re-run: `go run ./tools/gen_cdfs > src/cdfs/generated.rs`")
	fmt.Fprintln(out, "// Source: github.com/KarpelesLab/goavif/av1/entropy/cdfs (MIT)")
	fmt.Fprintln(out, "//")
	fmt.Fprintln(out, "// Tables are wire-format: `cdf[0..N-2]` = Q15 P(X>i)*32768 (decreasing),")
	fmt.Fprintln(out, "// `cdf[N-1]` = 0 sentinel, `cdf[N]` = update counter (starts at 0).")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "#![allow(clippy::all)]")
	fmt.Fprintln(out, "#![allow(dead_code)]")
	fmt.Fprintln(out, "")

	// Reflect into the cdfs package via a small registry. We can't
	// enumerate package-level vars directly, so list them explicitly.
	// Additions should be mirrored here and in the test that checks
	// round-trip byte counts.
	registry := registerCDFs()
	names := make([]string, 0, len(registry))
	for n := range registry {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, n := range names {
		emit(out, n, registry[n])
	}
}

// registerCDFs returns a map from exported name → reflect.Value. Listed
// by hand because Go reflection can't walk package-level vars of an
// imported package. New CDFs added to goavif must be appended here.
func registerCDFs() map[string]reflect.Value {
	return map[string]reflect.Value{
		"DefaultAngleDeltaCDF":        reflect.ValueOf(cdfs.DefaultAngleDeltaCDF),
		"DefaultCFLAlphaCDF":          reflect.ValueOf(cdfs.DefaultCFLAlphaCDF),
		"DefaultCFLSignCDF":           reflect.ValueOf(cdfs.DefaultCFLSignCDF),
		"DefaultCoeffBaseEOBMultiCDF": reflect.ValueOf(cdfs.DefaultCoeffBaseEOBMultiCDF),
		"DefaultCoeffBaseMultiCDF":    reflect.ValueOf(cdfs.DefaultCoeffBaseMultiCDF),
		"DefaultCoeffBrMultiCDF":      reflect.ValueOf(cdfs.DefaultCoeffBrMultiCDF),
		"DefaultDCSignCDF":            reflect.ValueOf(cdfs.DefaultDCSignCDF),
		"DefaultDrlCDF":               reflect.ValueOf(cdfs.DefaultDrlCDF),
		"DefaultEOBExtraCDF":          reflect.ValueOf(cdfs.DefaultEOBExtraCDF),
		"DefaultEOBMulti1024CDF":      reflect.ValueOf(cdfs.DefaultEOBMulti1024CDF),
		"DefaultEOBMulti128CDF":       reflect.ValueOf(cdfs.DefaultEOBMulti128CDF),
		"DefaultEOBMulti16CDF":        reflect.ValueOf(cdfs.DefaultEOBMulti16CDF),
		"DefaultEOBMulti256CDF":       reflect.ValueOf(cdfs.DefaultEOBMulti256CDF),
		"DefaultEOBMulti32CDF":        reflect.ValueOf(cdfs.DefaultEOBMulti32CDF),
		"DefaultEOBMulti512CDF":       reflect.ValueOf(cdfs.DefaultEOBMulti512CDF),
		"DefaultEOBMulti64CDF":        reflect.ValueOf(cdfs.DefaultEOBMulti64CDF),
		"DefaultInterpFilterCDF":      reflect.ValueOf(cdfs.DefaultInterpFilterCDF),
		"DefaultIntraExtTxCDFSet1":    reflect.ValueOf(cdfs.DefaultIntraExtTxCDFSet1),
		"DefaultIntraExtTxCDFSet2":    reflect.ValueOf(cdfs.DefaultIntraExtTxCDFSet2),
		"DefaultIsInterCDF":           reflect.ValueOf(cdfs.DefaultIsInterCDF),
		"DefaultKfYModeCDF":           reflect.ValueOf(cdfs.DefaultKfYModeCDF),
		"DefaultMvBitsCDF":            reflect.ValueOf(cdfs.DefaultMvBitsCDF),
		"DefaultMvClass0BitCDF":       reflect.ValueOf(cdfs.DefaultMvClass0BitCDF),
		"DefaultMvClass0FrCDF":        reflect.ValueOf(cdfs.DefaultMvClass0FrCDF),
		"DefaultMvClass0HpCDF":        reflect.ValueOf(cdfs.DefaultMvClass0HpCDF),
		"DefaultMvClassCDF":           reflect.ValueOf(cdfs.DefaultMvClassCDF),
		"DefaultMvFrCDF":              reflect.ValueOf(cdfs.DefaultMvFrCDF),
		"DefaultMvHpCDF":              reflect.ValueOf(cdfs.DefaultMvHpCDF),
		"DefaultMvJointCDF":           reflect.ValueOf(cdfs.DefaultMvJointCDF),
		"DefaultMvSignCDF":            reflect.ValueOf(cdfs.DefaultMvSignCDF),
		"DefaultNewMvCDF":             reflect.ValueOf(cdfs.DefaultNewMvCDF),
		"DefaultPartitionCDF":         reflect.ValueOf(cdfs.DefaultPartitionCDF),
		"DefaultRefMvCDF":             reflect.ValueOf(cdfs.DefaultRefMvCDF),
		"DefaultSingleRefCDF":         reflect.ValueOf(cdfs.DefaultSingleRefCDF),
		"DefaultSkipCDF":              reflect.ValueOf(cdfs.DefaultSkipCDF),
		"DefaultSkipModeCDF":          reflect.ValueOf(cdfs.DefaultSkipModeCDF),
		"DefaultSpatialPredSegTreeCDF": reflect.ValueOf(cdfs.DefaultSpatialPredSegTreeCDF),
		"DefaultTxSizeCDF":            reflect.ValueOf(cdfs.DefaultTxSizeCDF),
		"DefaultTxbSkipCDF":           reflect.ValueOf(cdfs.DefaultTxbSkipCDF),
		"DefaultTxfmPartitionCDF":     reflect.ValueOf(cdfs.DefaultTxfmPartitionCDF),
		"DefaultUVModeCDF":            reflect.ValueOf(cdfs.DefaultUVModeCDF),
		"DefaultYModeCDF":             reflect.ValueOf(cdfs.DefaultYModeCDF),
		"DefaultZeroMvCDF":            reflect.ValueOf(cdfs.DefaultZeroMvCDF),
	}
}

// emit writes one `pub static NAME: <type> = <value>;` declaration.
// Walks the reflect.Value recursively:
//
//   - cdfs.CDF (= []uint16)       → `[u16; N]`
//   - [N]cdfs.CDF                 → `[&'static [u16]; N]` (jagged: inner
//     CDFs in the same outer array can
//     have different lengths)
//   - [N][M]cdfs.CDF etc.         → nested array of the above.
func emit(out *os.File, name string, v reflect.Value) {
	rustName := rustifyName(name)
	shape, innerLen, jagged := describeShape(v)
	typeStr := rustType(shape, innerLen, jagged)

	fmt.Fprintf(out, "pub static %s: %s = ", rustName, typeStr)
	emitValue(out, v, 0)
	fmt.Fprintln(out, ";")
	fmt.Fprintln(out, "")
}

// describeShape inspects the outer array dimensions up to the leaf CDF.
// Returns the list of outer dims (excluding the inner uint16 axis), the
// inner length if uniform across all leaves (0 if jagged), and a flag
// for the jagged case.
func describeShape(v reflect.Value) (dims []int, innerLen int, jagged bool) {
	dims = []int{}
	t := v.Type()
	for t.Kind() == reflect.Array {
		dims = append(dims, t.Len())
		t = t.Elem()
	}
	// t is now the leaf: cdfs.CDF (= []uint16) or []uint16.
	lengths := map[int]struct{}{}
	visitLeaves(v, func(leaf reflect.Value) {
		lengths[leaf.Len()] = struct{}{}
	})
	if len(lengths) == 1 {
		for L := range lengths {
			innerLen = L
		}
	} else {
		jagged = true
	}
	return
}

func visitLeaves(v reflect.Value, fn func(reflect.Value)) {
	if v.Kind() == reflect.Slice {
		fn(v)
		return
	}
	if v.Kind() == reflect.Array {
		for i := 0; i < v.Len(); i++ {
			visitLeaves(v.Index(i), fn)
		}
		return
	}
}

func rustType(dims []int, _ int, _ bool) string {
	// Leaf is always `&'static [u16]` — lets jagged tables (mixed CDF
	// lengths, e.g. partition) coexist with uniform ones in the same
	// declaration, and keeps the emitted syntax uniform for a simple
	// scalar CDF.
	s := "&'static [u16]"
	for i := len(dims) - 1; i >= 0; i-- {
		s = fmt.Sprintf("[%s; %d]", s, dims[i])
	}
	return s
}

func emitValue(out *os.File, v reflect.Value, depth int) {
	indent := strings.Repeat("    ", depth)
	if v.Kind() == reflect.Slice {
		// Leaf CDF: emit as `&[a, b, c, 0, 0]`.
		fmt.Fprint(out, "&[")
		for i := 0; i < v.Len(); i++ {
			if i > 0 {
				fmt.Fprint(out, ", ")
			}
			fmt.Fprintf(out, "%d", v.Index(i).Uint())
		}
		fmt.Fprint(out, "]")
		return
	}
	if v.Kind() == reflect.Array {
		// Outer array.
		fmt.Fprint(out, "[\n")
		for i := 0; i < v.Len(); i++ {
			fmt.Fprint(out, indent+"    ")
			emitValue(out, v.Index(i), depth+1)
			fmt.Fprint(out, ",\n")
		}
		fmt.Fprint(out, indent+"]")
		return
	}
	panic(fmt.Sprintf("unexpected kind %v", v.Kind()))
}

// rustifyName converts DefaultPartitionCDF → DEFAULT_PARTITION_CDF.
func rustifyName(name string) string {
	var b strings.Builder
	for i, r := range name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			prev := rune(name[i-1])
			if !(prev >= 'A' && prev <= 'Z') {
				b.WriteRune('_')
			} else if i+1 < len(name) {
				next := rune(name[i+1])
				if next >= 'a' && next <= 'z' {
					b.WriteRune('_')
				}
			}
		}
		b.WriteRune(r)
	}
	return strings.ToUpper(b.String())
}
